# ======================== Elasticsearch Configuration =========================
# The es_yaml top level key contains whatever data will be written to elasticsearch.yml
#
[es_yaml]
  [es_yaml.bootstrap]
    memory_lock = false  #true

  [es_yaml.cluster]
    name = "chef-insights"
    [es_yaml.cluster.routing.allocation.disk.watermark]
      low = "85%"
      high = "90%"
      flood_stage = "95%"

  [es_yaml.discovery.zen]
    minimum_master_nodes = 1

  [es_yaml.http]
    port = 9200

  [es_yaml.transport.tcp]
    port = 9300

  [es_yaml.indices.recovery]
    max_bytes_per_sec = "250mb"

  [es_yaml.network]
    host = "0.0.0.0"

  [es_yaml.node]
    max_local_storage_nodes = 1

  [es_yaml.path]
    data = "/hab/svc/automate-ha-elasticsearch-copy/data"
    logs = "/hab/svc/automate-ha-elasticsearch-copy/logs"

# Runtime settings for jvm.options and the systemd service
[runtime]
  max_open_files = ""
  max_locked_memory = ""
  es_startup_sleep_time = ""
  # This config variable becomes the value of ES_JAVA_OPTS.
  # Note: JVM values for -Xms and -Xmx are auto calculated in the run hook.
  # Any value defined here will override the calculation in the hook.
  es_java_opts = ""
  # It looks like the default NewRatio is ignored when setting UseConcMarkSweepGC
  # https://bugs.openjdk.java.net/browse/JDK-8153578. If we set it explicitly we
  # can get the expected behavior
  new_ratio = 2

# This section contains any settings that need to applied on startup for opendistro.
# Any values put under this hash will be rendered into yaml and applied with
# securityadmin.sh. These should be your basic admin credentials, as long term you
# can manage your creds outside of habitat with securityadmin.sh.

[opendistro_auth]
  admin_username = "admin"
  admin_password = "admin"
  dashboard_username = "kibana"
  dashboard_password = "kibana"

# Fill these in in your user.toml to override automatic SSL Cert generation
[opendistro_ssl]

