# WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
#
# If you are modifying this file, you almost surely also want to
# modify pkg/es/config_request.go. The DefaultConfigRequest() function
# sets all of the real defaults.
#
# The duplication is necessary currently since our tests and studio
# require automate-elasticsearh be launchable without the deployment
# service.
#
# WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
[cluster]
  #
  # Use a descriptive name for your cluster:
  #
  name = "opensearch"

  [cluster.routing.allocation]
    #
    # How many concurrent shard recoveries are allowed to happen on a node.
    # Defaults to 2.
    #
    node_concurrent_recoveries = "2"
    #
    # While the recovery of replicas happens over the network, the recovery of
    # an unassigned primary after node restart uses data from the local disk.
    # These should be fast so more initial primary recoveries can happen in
    # parallel on the same node. Defaults to 4.
    #
    node_initial_primaries_recoveries = "4"
    #
    # Allows to perform a check to prevent allocation of multiple instances of
    # the same shard on a single host, based on host name and host address.
    # Defaults to false, meaning that no check is performed by default. This
    # setting only applies if multiple nodes are started on the same machine.
    #
    same_shard_host = "false"
    #
    # https://www.elastic.co/guide/en/elasticsearch/reference/2.3/allocation-awareness.html
    #
    awareness_attributes = ""
#
# ------------------------------------ Node ------------------------------------
#
[node]
  # Use a descriptive name for the node:
  #
  name = ""
  #
  # Add custom attributes to the node:
  #
  # node.rack: r1
  #
  rack_id = ""
  zone    = ""
  #
  # Disable starting multiple nodes on a single system:
  #
  max_local_storage_nodes = 1
  #
  # Configure node as master-only, master-eligible, data-only, or client
  # (https://www.elastic.co/guide/en/elasticsearch/reference/2.3/modules-node.html#master-node)
  # Default is master-eligible (master and data are both "true")
  #
  master = true
  data   = true

#
# ----------------------------------- Paths ------------------------------------
#
[path]
  #
  # Path to directory where to store the data (separate multiple locations by comma):
  #
  data =    ""
  #
  # Path to log files:
  #
  logs =    "logs"
  #
  # Path to backup repository
  repo = ""

#
# ----------------------------------- Indices ----------------------------------
#
[indices]
  [indices.recovery]
    max_bytes_per_sec  =            "20mb"

  [indices.fielddata]
    #
    # The max size of the field data cache, eg 30% of node heap space, or an absolute
    # value, eg 12GB. Defaults to unbounded.
    #
    cache_size =                   ""

  [indices.breaker]
    #
    # Starting limit for overall parent breaker, defaults to 70% of JVM heap.
    #
    total_limit =                    "70%"
    #
    # Limit for fielddata breaker, defaults to 60% of JVM heap.
    #
    fielddata_limit =                "60%"
    #
    # A constant that all field data estimations are multiplied with to determine a
    # final estimation. Defaults to 1.03
    #
    fielddata_overhead =             "1.03"
    #
    # Limit for request breaker, defaults to 40% of JVM heap.
    #
    request_limit =                  "40%"
    #
    # A constant that all request estimations are multiplied with to determine a
    # final estimation. Defaults to 1.
    #
    request_overhead =               "1"

#
# ----------------------------------- Memory -----------------------------------
#
[bootstrap]
  # Lock the memory on startup:
  #
  memory_lock = false
  #
  # Make sure that the heap size is set to about half the memory available
  # on the system and that the owner of the process is allowed to use this
  # limit.
  #
  # Elasticsearch performs poorly when the system is swapping the memory.
  #

#
# ---------------------------------- Network -----------------------------------
#
[network]
  #
  # Set the bind address to a specific IP (IPv4 or IPv6):
  #
  host =  "0.0.0.0"
  #
  # Set a custom port for HTTP:
  #
  port = 9200
  #
  # For more information, see the documentation at:
  # <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html>

[transport]
  port = 9300

#
# --------------------------------- Discovery ----------------------------------
#
[discovery]
  # Pass an initial list of hosts to perform discovery when new node is started:
  # The default list of hosts is ["127.0.0.1", "[::1]"]
  #
  ping_unicast_hosts = "[]"
  #
  # Prevent the "split brain" by configuring the majority of nodes (total number of nodes / 2 + 1):
  #
  minimum_master_nodes = 1
  #
  # For more information, see the documentation at:
  # <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery.html>
  #
  zen_fd_ping_timeout = "30s"

#
# ---------------------------------- Gateway -----------------------------------
#
[gateway]
  #
  # Block initial recovery after a full cluster restart until N nodes are started:
  #
  recover_after_nodes   = ""
  #
  # The number of (data or master) nodes that are expected to be in the cluster.
  # Recovery of local shards will start as soon as the expected number of nodes
  # have joined the cluster. Defaults to 0
  #
  expected_nodes        = "0"
  #
  # The number of master nodes that are expected to be in the cluster. Recovery
  # of local shards will start as soon as the expected number of master nodes
  # have joined the cluster. Defaults to 0
  #
  expected_master_nodes = "0"
  #
  # The number of data nodes that are expected to be in the cluster. Recovery of
  # local shards will start as soon as the expected number of data nodes have
  # joined the cluster. Defaults to 0
  #
  expected_data_nodes   = "0"
  #
  # If the expected number of nodes is not achieved, the recovery process waits
  # for the configured amount of time before trying to recover regardless.
  # Defaults to 5m if one of the expected_nodes settings is configured.
  #
  recover_after_time    = ""
  #
  # For more information, see the documentation at:
  # <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-gateway.html>
  #

#
# ---------------------------------- Various -----------------------------------
#
[action]
  #
  # Require explicit names when deleting indices:
  #
  destructive_requires_name  = "true"

# ======================== Elasticsearch Logger Configuration =========================
[logger]
  level = "info"

# ======================== Elasticsearch Plugins Configuration =========================
[plugins]
  cloud_aws_signer = ""
  #security.ssl.http.enabled = false
# ======================== Runtime Configuration =========================
[runtime]
  max_open_files = ""
  max_locked_memory = "unlimited"
  es_startup_sleep_time = ""
  es_java_opts = ""
  heapsize = "2g"

[deprecated]
external_es = false

[tls]
# root pem cert that signed the two cert/key pairs below
rootCA = """-----BEGIN CERTIFICATE-----
MIIDnTCCAoWgAwIBAgIJAMEzwdWMbY/0MA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRow
GAYDVQQKDBFDaGVmIFNvZnR3YXJlIEluYzETMBEGA1UEAwwKY2hlZnJvb3RjYTAe
Fw0yMjA0MDUxMTU5MDVaFw0yNTA0MDQxMTU5MDVaMGUxCzAJBgNVBAYTAlVTMRMw
EQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRowGAYDVQQKDBFD
aGVmIFNvZnR3YXJlIEluYzETMBEGA1UEAwwKY2hlZnJvb3RjYTCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAK2vIRRl/h6XzHD1MAUF1Sp4Wms1ObwgNb5k
nC1HAJ6v0sPuXPPIot439/cyj/Uk0lIaXqIPFcCoKsmklIEhFawctLHT6QSSb6EO
O1tk5o/ltJSf5DHRyJSb1erJYZzkNXxrhVSJhSTD3E0TXoqDGz8oWn+jBmh6l/D4
oJHDKi8zKCPQOXJQg4pJ3K2Pi/ynL+pDPj8H1HTBjivg4nDzCtLZb2bctJIJb6xm
WbQur3+lO+quAzroeVFR9xZIlkyRcCRoamOwcPGeTj6eb06DTMd4rmYin55Mh3eU
s287B4IJblp1xhl4QSpsh2wqeEWaUrr4l+IqnotJUcgkDa6PHUUCAwEAAaNQME4w
HQYDVR0OBBYEFP8FyiA6RCYBpPD+FbzydjfTImdPMB8GA1UdIwQYMBaAFP8FyiA6
RCYBpPD+FbzydjfTImdPMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
AA+9ti0qSD70AAZi7bzbmxtJ2ewDxOKC7Y10GavVXHNajuy8i01dIIkCo9uCMWyY
qCQdOCS6G/Ee53lsFNuONfas/ByVjaVHMg8CV1EcI7s67UxvyzCeddMLsTUWpHY4
Li5yb3AKasYltAE3ZSVYvl8Q4LBYxb+ukPQLOb9migRvJdZmaWr6NmSbi018i4uz
B9Syk8pFKjE30qwmB7CY4hDExj66CHX1lhQ1EcZyL+HzTHE1tHN2w29nnmo8pE5I
HayqBGRBqaVLPBEigY7vqi5C7sU0WpQJvcRBqTl4BztwI6sz+WjCMs0tBfkFzIaO
xgiiAhyV27Zkg2Gd1TkXOpo=
-----END CERTIFICATE-----"""
# Certificate used for admin actions against https://9200
admin_cert = """-----BEGIN CERTIFICATE-----
MIIDRTCCAi0CCQCNZuc0I0tg1jANBgkqhkiG9w0BAQsFADBlMQswCQYDVQQGEwJV
UzETMBEGA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UE
CgwRQ2hlZiBTb2Z0d2FyZSBJbmMxEzARBgNVBAMMCmNoZWZyb290Y2EwHhcNMjIw
NDA1MTE1OTA1WhcNMjUwNDA0MTE1OTA1WjBkMQswCQYDVQQGEwJVUzETMBEGA1UE
CAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UECgwRQ2hlZiBT
b2Z0d2FyZSBJbmMxEjAQBgNVBAMMCWNoZWZhZG1pbjCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBALcAjnQOK82kS/5pncdg0A/DzzDtJqdD350ZY+WlpAzQ
+zIv1eJkh3SkR0+nOLvAW943YsZzQp+m5tYt0pnlJS2YqouIh6s3PM5HjIyVtAd3
Q3LIFi1zdzqiAGg69H5FB/Vz8sPoadh53/+SW5qGSswxE4bIdywDZ9TX1zd4p8NY
ouL/MkaS1mXfzT0/acUhqQuFnZK0Umn9ICP7Y7rvs2BWVzp7MWppMOPuja8FBvPz
aKPs1r6XIK8LpGEBCO7Sg9+LmPFkxLCIIeCFJ6he/mm3fmofJS0k43Eeo+tHBUA3
MHPGkN2dgECrXhVNEANbsgB3pgi//Onx+Thdggri628CAwEAATANBgkqhkiG9w0B
AQsFAAOCAQEAbc781OIEo4BGO4WUh5nESw4RtKUqVGcINGkxfRMub1IfE85C+K+V
2eFY2eEk1tx3E3sFL4QCy6KKCvJoRJSTIrGNlFf5zn89x01U1kbDQ8Ne9Z6XLl3f
Qy9bVQppQfbwAEFXNdoMkMjfQO2Q7/P9DIQjRMgun6uUqYQw62obwOTNC/mKE8uf
18raFnnRvQ9qHfrcWK5tAH3sVCaTf0GbnXLlqNyMRTZuSXW3KI5wdEAUOxBeyPf/
AiGkb3vIvOu46g2m3/gWPCkiZk0SbFYQ/BLoLQUYgQnr0STQq95GTvgZkJG1D0K6
UaDQRWAeQjoKWQhi1feWckXJG63TYMCRsw==
-----END CERTIFICATE-----"""
# the private key associated with the above pem cert
admin_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC3AI50DivNpEv+
aZ3HYNAPw88w7SanQ9+dGWPlpaQM0PsyL9XiZId0pEdPpzi7wFveN2LGc0KfpubW
LdKZ5SUtmKqLiIerNzzOR4yMlbQHd0NyyBYtc3c6ogBoOvR+RQf1c/LD6GnYed//
kluahkrMMROGyHcsA2fU19c3eKfDWKLi/zJGktZl3809P2nFIakLhZ2StFJp/SAj
+2O677NgVlc6ezFqaTDj7o2vBQbz82ij7Na+lyCvC6RhAQju0oPfi5jxZMSwiCHg
hSeoXv5pt35qHyUtJONxHqPrRwVANzBzxpDdnYBAq14VTRADW7IAd6YIv/zp8fk4
XYIK4utvAgMBAAECggEAIbv/hpNKLdlYjOiJRkSpdg6BdiJxWqofYYVZre6v5BDu
DV1WDyq68ZyK7LsFsU6PYNJS6gQ7RtTsfpTp2qasCNC4t4oOgFhpZBk6Znv+ONYa
X+FUfUJouy075/reMRymj++007pXMKmeyiz/p+eTiDqPv+vaVAm4rTqwmLAsNM0l
HIhyYMDZu1iNOtSfXrtI4LCB2THEmkJd9Ixe6HECETJdzn2mfl3KVrkqxSnZJn0w
uq6kAaMvL1pZQjDDhzuLf0W6tJ63Ae6cHg7D254CQZjkbPscsnz7FBXU+cNx8PRw
4Pjs3zyQTLBO17sXIj1qCuityvZIX2zzDAAhusb0gQKBgQDmgNvPvphgxRUcjf4z
XAQxK0cn5L/2a16WkjiiQ++kNHYe4GX1o7BmRW7wpBc4DwQ09oJcL/vNVqrQKY38
jkEEDEOK4q1nISRRKzQX/s7Q2k699dO7dJEHAfos3b9CFueZQw7YXEkUGvYoXAM8
/0GwnRGjmICai1d5xx/RDqWjLwKBgQDLPpyIHlcCKHIv8gdLknxjTPwERn2MteUT
SXPaxSFxw/h7olUJrpnsaCJ4vJizh8u5hJ3km83jrqH0el4ujqfcXgJx+8jQH1KQ
uHn7P3zFNNFIdNAdCrJiYGrF7oUerH3v8pzwgfo5pT1IXtQSmeJajNpEDR4mmQ+L
A2hqrYYrwQKBgDBuXsEVoNqkTj1DsGeGK/NQzpCZRaQ3BxbH/lJJx+5Of4sZRxMH
o6a5bAfv0lka/p1KNjW8d0G7tgQq1wR7tzlsgjyKSDjlA8ZyN23bQgUr+WN8ZVJ7
uYUpazFGHkt6mIrhRhs7uLcauyHbw2prj5fWSMCA6HSQVn7l0c+RLkhNAoGAMaKP
zbpDG3bPNCBSYcVbdVDGtzCT1rpRQF2O2p2L5mGqnF7vj5bBZnej+4JrdGS0fxEB
EmRuaq0qRi9gMtSJ8ApRZI7N4u3TVx6GQ7KkgPC+L4i/jmgfWmEbkk0G24/aja/d
XesQNeXBypvGBOjp251MbJQbieeVYSiq5mqMOsECgYEAzJWejLbOxnMbv3KL1NAC
PH3W5r7rUMncKWdSib6W063QWs9xhicGh9zaoWLSdyVJfVHmk16wyleuRUhaII3a
qM6I1APdS5ONlP2e08ZhYxX5cDE+/VzhvzwjMT59WTse1Yy3pZDUkzPkD2ZZiL9m
sQF7g7l18zayzPAJfBej4A0=
-----END PRIVATE KEY-----"""
# Certificate used for intracluster ssl on port 9300
ssl_cert = """-----BEGIN CERTIFICATE-----
MIIDRDCCAiwCCQCNZuc0I0tg1zANBgkqhkiG9w0BAQsFADBlMQswCQYDVQQGEwJV
UzETMBEGA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UE
CgwRQ2hlZiBTb2Z0d2FyZSBJbmMxEzARBgNVBAMMCmNoZWZyb290Y2EwHhcNMjIw
NDA1MTE1OTA1WhcNMjUwNDA0MTE1OTA1WjBjMQswCQYDVQQGEwJVUzETMBEGA1UE
CAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UECgwRQ2hlZiBT
b2Z0d2FyZSBJbmMxETAPBgNVBAMMCGNoZWZub2RlMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEA264M8i8lwy67do0CvoqXdXKt1Sqha0MvDzToHiIYLZ6M
TDOzyyAB3CmmpsXr4CCLmbXmHsaDd3OP5cy/RrWjIl8IJrrZzCIG1LPESV0+KLqf
1YoVoZhunnpW+Gc/c5Jw/BavoIsiYP8+ClCjTl4iIbKTsdZaDmD/cUk4GPv38/4R
85JAM1EZRrLsPbuMFnJoefBusgsPFwFw7DKW2qbN6gMeq9pHXQXSXmNOkoW59DSw
sdx9799+DIb56wh6EtLlujorK8rI7fcSRrA1IxT+tTPVatrkDuNOWeG9+2BhBCs6
spH6HFYNg4HqIIk0uTVJAorm6Uxk5/QtKb1XSWkHawIDAQABMA0GCSqGSIb3DQEB
CwUAA4IBAQCAqRrKcXWxblxnKWDrCn3OY09Tu3+Ogge5StqcqrWSmhgNwsjf5sYz
VXvH5MP28KxrjN8xT+X1OMv4junr8UFof7vqIGkyEi8tTXEvBOux2w/v1A36Dpey
HeQHBJkiit5MjVoRNfkciFFuJaFRG31sZ6tVj9enUDc/Fm0O1cp2uR9kVu/VVRxy
agniu3lxt8YbYzc9t38k6UR84iBQ/iuuVdv+9tv0B4qomajCRbPkNovJW23TPZTV
s32puz6FOVQUgsl2u3mT72JRPT6ELxsWTgaK6rOzYnVbapayLlzf/NeLAgHjnQjo
gOwAbYW2icyxBb7QsPzHmBPppa0ADuWZ
-----END CERTIFICATE-----"""
# the private key associated with the above pem cert
ssl_key = """-----BEGIN PRIVATE KEY-----
MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQDbrgzyLyXDLrt2
jQK+ipd1cq3VKqFrQy8PNOgeIhgtnoxMM7PLIAHcKaamxevgIIuZteYexoN3c4/l
zL9GtaMiXwgmutnMIgbUs8RJXT4oup/VihWhmG6eelb4Zz9zknD8Fq+giyJg/z4K
UKNOXiIhspOx1loOYP9xSTgY+/fz/hHzkkAzURlGsuw9u4wWcmh58G6yCw8XAXDs
Mpbaps3qAx6r2kddBdJeY06Shbn0NLCx3H3v334MhvnrCHoS0uW6Oisrysjt9xJG
sDUjFP61M9Vq2uQO405Z4b37YGEEKzqykfocVg2DgeogiTS5NUkCiubpTGTn9C0p
vVdJaQdrAgMBAAECggEBAL5pBXWh4iRkzD48iUVo0VEOvpfG5LUZPZ/7prn/qV9Z
Tpf6NHv62UHgpD9nzESvUPFBlh3UyTzvYKm5p419gNIY9vLDAGcMk0koLBm/BVK+
OC4aCxfPDQq2Vc3niDr/kokejMol7v2OH1NHg9U4iHMW2yfI+LP/5UlnQoV9WPUV
BmausNDC291eKTA/SC9B++zjeDcdl9IGpQiBSNsNCcbKChpRBqtMki/dTq180e0F
N+OxDxv9kIe3CqdFOZVggVMa0rhW8Oyeb7mM7O2eP5MZmOIGKgvwKhQw98zO6vjd
9FzaWoS9vibcwCQTA3u+JcPKa6zUOf9UUSLtJysj7PkCgYEA/9YCLb2wf6OjhPG7
5Cea2rv5Ga+1SQIY/Eb2+ew7ku1My+eAzj3kl7PfkV+r4WFzbAgnPDKWM52f8ZRp
Ovm9TkgxnfZuHaLUjpi6N7y5K/28yhCEuFDbnvdyj5P2IVnUCshCZxckvQCD7cOO
s2Sr16oLPbVtaSgbazGcETEP5/UCgYEA29Ibi8kNI89HfZ72wN/0rw5F1TYnQH9V
ul8gRQJ5Us9gTQq8/AQB+lc77Ff02RL/+oUeam8my2cz2eetkbqn/J8ToA3z8Ud4
I5tfYCbJgm3gDutZ6mLvrZkohYgt+3jIBN5g5pK0YuHvH3PmDTDIZx7SYNoQI16L
/CGEiEF/dd8CgYEAq+AeFJbUxdutFrrErVJCQeN5Rd164HKtUIdok502pM4SAwcj
zOtd8OEiOOtacQ9kWNbdbR7bNBAYjVdUnw97M+VimCof7n8faDGJIbsDeF9+fw47
7Aw+j/zUFUulVuCfiSLjIZk10FhRSeJQs4rVvAz8gleqCrSsPwbUP+SDOCUCgYEA
pCN3PiGaFisojrysM8kGw9A8hMAy/w4VzVxKlD0MqrD+j4h9JRE5CN0qeYgT5CMz
0LSlyYPFzAv7w7IjALYHybJezRyeEoPzSWMzDHDp9uJkc795HHNT1KSQhWTyMNw3
PqtuX70bxNo/25SHK0JJ4fY50OgDNOXcUSAV/kgqDLECgYEAsjCelZgrMMZhxx0K
CtlIhaQCweL6E0GI0jnl5WfHwkzVY8ye2t+lWlEp5dJv8XanShL9Nt5mg1RH3m9v
oCalJqS4UzPyNpJul7CgUFstxRk35k4Pr4oVS4TN7wBLq5vMNCDlOSTipxZKbEJr
qyhbKeFAbN8SrrO1Hcdth5ZsbaE=
-----END PRIVATE KEY-----"""
